name: C/C++ CI

on:
  push:
    branches: [ development/main ]
  pull_request:
    branches: [ development/main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Navigate into folder
      run: cd asio-wrapper
    - name: Create build folder
      run: mkdir build
    - name: Navigate into build folder
      run: cd build
    - name: Check path
      run: pwd
    - name: Check contents
      run: ls -l
    - name: Initialize cmake
      run: cmake ..
    - name: Run make
      run: make
