name: C/C++ CI

on:
  push:
    branches: [ development/main ]
  pull_request:
    branches: [ development/main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build setup
      shell: bash
      run: |
        pwd
        ls -l
        build
        cd build
        pwd
        ls -l
        ls -l ..
        cmake --version
        make --version
        g++ --version
