name: C/C++ CI

on:
  push:
    branches: [ development/main ]
  pull_request:
    branches: [ development/main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create build folder
      run: mkdir -p asio-wrapper/build
    - name: Navigate into folder
      run: cd asio-wrapper/build
    - name: Initialize cmake
      run: cmake ..
    - name: Run make
      run: make
