name: C/C++ CI

on:
  push:
    branches: [ development/main ]
  pull_request:
    branches: [ development/main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup cmake
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ..
    - name: Build with make
      shell: bash
      run: |
        make
